apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argocd
  name: argocd
spec:
  replicas: 4
  selector:
    matchLabels:
      app: argocd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argocd
    spec:
      containers:
      - image: nginx:1.14
        name: nginx
        resources: {}
status: {}
